apiVersion: v1
kind: Service
metadata:
  name: petclinic-k8s
  labels:
    app: petclinic-k8s
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    app: petclinic-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-k8s
  template:
    metadata:
      labels:
        app: petclinic-k8s
    spec:
      containers:
      - name: petclinic-k8s
        image: racerm3/springboot-petclinic:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
