# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B install --file pom.xml -DskipTests
    
    - name: Build Docker Image
      working-directory: ./spring-petclinic-server
      run: mvn -B package docker:build --file pom.xml -DskipTests
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./spring-petclinic-server
        file: ./spring-petclinic-server/src/main/docker/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: racerm3/spring-petclinic:latest
